version: '2'
services:
  itcenterbaza-app:
    image: itcenterbaza
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://itcenterbaza-postgresql:5432/itcenterbaza
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  itcenterbaza-postgresql:
    extends:
      file: postgresql.yml
      service: itcenterbaza-postgresql
